
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action helpAction;

	private global::Gtk.Action HelpAction1;

	private global::Gtk.Action HelpAction2;

	private global::Gtk.Action ControlsAction;

	private global::Gtk.Alignment alignment1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.MenuBar menubar5;

	private global::Gtk.HBox mainWindowSeparationBox;

	private global::Gtk.Alignment alignment2;

	private global::Gtk.Frame wiimoteFrame;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Button connectButton;

	private global::Gtk.Button calibrateButton;

	private global::Gtk.Button disconnectButton;

	private global::Gtk.Label wiimoteFrameLabel;

	private global::Gtk.Alignment alignment3;

	private global::Gtk.Frame feedbackFrame;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.VBox vbox4;

	private global::Gtk.CheckButton vibrationCheckbutton;

	private global::Gtk.Image feedbackImage;

	private global::Gtk.Label feedbackFrameLabel;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.helpAction = new global::Gtk.Action("helpAction", null, null, "gtk-help");
		w1.Add(this.helpAction, null);
		this.HelpAction1 = new global::Gtk.Action("HelpAction1", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction1, null);
		this.HelpAction2 = new global::Gtk.Action("HelpAction2", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction2, null);
		this.ControlsAction = new global::Gtk.Action("ControlsAction", global::Mono.Unix.Catalog.GetString("Controls"), null, null);
		this.ControlsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Controls");
		w1.Add(this.ControlsAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("OsuMote");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar5\'><menu name=\'HelpAction2\' action=\'HelpAction2\'><menui" +
				"tem name=\'ControlsAction\' action=\'ControlsAction\'/></menu></menubar></ui>");
		this.menubar5 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar5")));
		this.menubar5.Name = "menubar5";
		this.vbox3.Add(this.menubar5);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.menubar5]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.mainWindowSeparationBox = new global::Gtk.HBox();
		this.mainWindowSeparationBox.Name = "mainWindowSeparationBox";
		this.mainWindowSeparationBox.Homogeneous = true;
		this.mainWindowSeparationBox.Spacing = 6;
		this.mainWindowSeparationBox.BorderWidth = ((uint)(3));
		// Container child mainWindowSeparationBox.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		// Container child alignment2.Gtk.Container+ContainerChild
		this.wiimoteFrame = new global::Gtk.Frame();
		this.wiimoteFrame.Name = "wiimoteFrame";
		this.wiimoteFrame.ShadowType = ((global::Gtk.ShadowType)(2));
		this.wiimoteFrame.BorderWidth = ((uint)(2));
		// Container child wiimoteFrame.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Homogeneous = true;
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(2));
		// Container child vbox1.Gtk.Box+BoxChild
		this.connectButton = new global::Gtk.Button();
		global::Gtk.Tooltips w3 = new Gtk.Tooltips();
		w3.SetTip(this.connectButton, "Attempt to connect to the wiimote via bluetooth", "Attempt to connect to the wiimote via bluetooth");
		this.connectButton.CanFocus = true;
		this.connectButton.Name = "connectButton";
		this.connectButton.UseUnderline = true;
		this.connectButton.Label = "Connect";
		this.vbox1.Add(this.connectButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.connectButton]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.calibrateButton = new global::Gtk.Button();
		w3.SetTip(this.calibrateButton, "Calibrate movement detection", "Calibrate movement detection");
		this.calibrateButton.Sensitive = false;
		this.calibrateButton.CanFocus = true;
		this.calibrateButton.Name = "calibrateButton";
		this.calibrateButton.UseUnderline = true;
		this.calibrateButton.Label = "Calibrate";
		this.vbox1.Add(this.calibrateButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.calibrateButton]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.disconnectButton = new global::Gtk.Button();
		w3.SetTip(this.disconnectButton, "Disconnect currently connected wiimote", "Disconnect currently connected wiimote");
		this.disconnectButton.Sensitive = false;
		this.disconnectButton.CanFocus = true;
		this.disconnectButton.Name = "disconnectButton";
		this.disconnectButton.UseUnderline = true;
		this.disconnectButton.Label = "Disconnect";
		this.vbox1.Add(this.disconnectButton);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.disconnectButton]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.GtkAlignment.Add(this.vbox1);
		this.wiimoteFrame.Add(this.GtkAlignment);
		this.wiimoteFrameLabel = new global::Gtk.Label();
		this.wiimoteFrameLabel.Name = "wiimoteFrameLabel";
		this.wiimoteFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Wiimote</b>");
		this.wiimoteFrameLabel.UseMarkup = true;
		this.wiimoteFrame.LabelWidget = this.wiimoteFrameLabel;
		this.alignment2.Add(this.wiimoteFrame);
		this.mainWindowSeparationBox.Add(this.alignment2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.mainWindowSeparationBox[this.alignment2]));
		w10.Position = 0;
		// Container child mainWindowSeparationBox.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		// Container child alignment3.Gtk.Container+ContainerChild
		this.feedbackFrame = new global::Gtk.Frame();
		this.feedbackFrame.Sensitive = false;
		this.feedbackFrame.Name = "feedbackFrame";
		this.feedbackFrame.ShadowType = ((global::Gtk.ShadowType)(2));
		this.feedbackFrame.BorderWidth = ((uint)(2));
		// Container child feedbackFrame.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vibrationCheckbutton = new global::Gtk.CheckButton();
		w3.SetTip(this.vibrationCheckbutton, "Enables vibration when a hit is registered", "Enables vibration when a hit is registered");
		this.vibrationCheckbutton.CanFocus = true;
		this.vibrationCheckbutton.Name = "vibrationCheckbutton";
		this.vibrationCheckbutton.Label = "Vibration";
		this.vibrationCheckbutton.DrawIndicator = true;
		this.vibrationCheckbutton.UseUnderline = true;
		this.vbox4.Add(this.vibrationCheckbutton);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vibrationCheckbutton]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox2.Add(this.vbox4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox4]));
		w12.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.feedbackImage = new global::Gtk.Image();
		this.feedbackImage.Name = "feedbackImage";
		this.feedbackImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("TRAB_IHC.res.TaikoNoInputs.png");
		this.vbox2.Add(this.feedbackImage);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.feedbackImage]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.GtkAlignment1.Add(this.vbox2);
		this.feedbackFrame.Add(this.GtkAlignment1);
		this.feedbackFrameLabel = new global::Gtk.Label();
		this.feedbackFrameLabel.Name = "feedbackFrameLabel";
		this.feedbackFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Feedback</b>");
		this.feedbackFrameLabel.UseMarkup = true;
		this.feedbackFrame.LabelWidget = this.feedbackFrameLabel;
		this.alignment3.Add(this.feedbackFrame);
		this.mainWindowSeparationBox.Add(this.alignment3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.mainWindowSeparationBox[this.alignment3]));
		w17.Position = 1;
		this.vbox3.Add(this.mainWindowSeparationBox);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.mainWindowSeparationBox]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.alignment1.Add(this.vbox3);
		this.Add(this.alignment1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 576;
		this.DefaultHeight = 275;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.KeyPressHandler);
		this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.KeyReleaseHandler);
		this.ControlsAction.Activated += new global::System.EventHandler(this.OnControlsActionActivated);
		this.connectButton.Clicked += new global::System.EventHandler(this.ConnectHandler);
		this.calibrateButton.Clicked += new global::System.EventHandler(this.CalibrateHandler);
		this.disconnectButton.Clicked += new global::System.EventHandler(this.DisconnectHandler);
		this.vibrationCheckbutton.Toggled += new global::System.EventHandler(this.ToggleVibrationHandler);
	}
}
